version: '3'

services:
  nginx-service:
    restart: always
    build:
      context: ./nginx-service
    ports:
      - '80:80'
    links:
      - auth-service
  auth-service:
    build:
      context: ./auth-service
    expose:
      - 3000
  redis:
    image: redis
    restart: always
    volumes:
      - ./storage/redis/data:/data
    ports:
      - '6379:6379'
    logging:
      driver: none