version: '3.1'

services:
  nginx-service:
    restart: always
    build:
      context: ./nginx-service
    ports:
      - '80:80'
    links:
      - auth-service
  auth-service:
    build:
      context: ./auth-service
    volumes:
      - "./lib-ts/:/usr/src/app/src/lib/"
    expose:
      - 3000
  redis-service:
    image: redis
    restart: always
    volumes:
      - ./storage/redis/data:/data
    expose:
      - 6379
    logging:
      driver: none